Filter top headline
PguOrange/NewsAndroid pull request #3
Opened 2020-06-22 09:53 UTC by martinsben

Ajout des filtres de pays et de catégorie pour les TopHeadlines

2020-06-22 09:54 UTC, martinsben commented
![](https://github.trello.services/images/mini-trello-icon.png) [[Headlines] Filtre de recherche](https://trello.com/c/cM52BfEb/18-headlines-filtre-de-recherche)

2020-06-23 14:40 UTC, PguOrange requested changes

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +                        text_category.text = topHeadlinesViewModel.textCategory
Attention quand on fait un when où on modifie de propriété de dedans comme `visibility` il faut être sûr qu'on la gère bien dans tous les cas.
On peut facilement tombé dans le piège où dans un cas on n'a pas géré notre propriété.
Par exemple `status_image.visibility` n'est pas géré dans toutes les conditions

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +                }
Un peu bizarre de faire un remove puis un add... 
Il n'y aurai pas un meilleur moyen de gérer tout ça ? 
Par exemple d'externaliser la gestion des categories dans un autre composant indépendant ?

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/repository/NewsRepository.kt
> +                    Log.d("refreshNews", "newsCollection is null")
Visuellement que se passe-t-il quand on est dans ce cas là ? c'est géré au niveau UI ?

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/repository/NewsRepository.kt
> +                    Log.d("refreshNews", "newsCollection is null")
Même remarque pour le `catch`

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +        }
Pourquoi avoir 2 swipes ?

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +enum class NewsApiStatus { LOADING, ERROR, ERRORWITHCACHE, ERRORWITHCACHEANDFILTERDISPLAYED, DONE }
Mettre des `_` pour les enum assez long sinon c'est un peu galère à lire

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +var currentCategory = Category.GENERAL.value
Pourquoi la variable est en dehors du model ?

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +    }
Pour info ici tu pourrais faire directement un `return when { ... }`

2020-06-23 14:40 UTC, PguOrange commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +    }
ha non sans le return en fait car tu modifies des propriétés

2020-06-23 14:40 UTC, PguOrange commented
Quand je switch entre les onglets je perd mes catégorie et ma langue.

2020-06-23 14:42 UTC, PguOrange commented
Pour la gestion des langues il serait pas mal d'avoir plutôt une liste déroulante avec le nom de la langue et un drapeau associé. Sinon on ne sais pas trop qu'il faut appuyer sur le bouton pour switch.
Désolé on n'a pas design et je n'ai pas assez détaillé les cartes pour mettre ce genre de choses...

2020-06-24 13:48 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +                        text_category.text = topHeadlinesViewModel.textCategory
abd682499bc0079af57ce90b72445fa6b1146398

2020-06-24 13:49 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +        }
abd682499bc0079af57ce90b72445fa6b1146398

2020-06-24 13:49 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +enum class NewsApiStatus { LOADING, ERROR, ERRORWITHCACHE, ERRORWITHCACHEANDFILTERDISPLAYED, DONE }
abd682499bc0079af57ce90b72445fa6b1146398

2020-06-24 15:07 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +var currentCategory = Category.GENERAL.value
189ad9d6f14cda570dbc20d601fc28e4520af384

2020-06-24 15:17 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesViewModel.kt
> +    }
e5893d0427c1c0b8e00b99e00e0655a8b682e3d0

2020-06-25 08:20 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/repository/NewsRepository.kt
> +                    Log.d("refreshNews", "newsCollection is null")
Maintenant c'est mieux géré, pour le try si il n'y a pas d'erreur lorsqu'on récupère les news : on affiche les news. Par contre sur NewsApi quand on met n'importe quoi dans country (fhjqfl au lieu de fr) et bien ça ne crée pas d'erreur, ça renvoie juste une liste de news vide avec comme totalResult = 0, du coup j'ai géré ça aussi. Donc quand totalResult = 0, j'affiche un Toast pour dire qu'il y a eu une erreur pour récupérer les news.

Et donc dans le catch, ça affiche aussi qu'il y a eu une erreur pour récupérer les news, mais pour arriver dans le catch il faut que l'appel à l'api reçoive une country null mais ce n'est pas vraiment possible car on accepte pas cela dans l'interface NewsApiService.

2020-06-25 08:22 UTC, martinsbenoit commented on app/src/main/java/com/example/newsandroid/repository/NewsRepository.kt
> +                    Log.d("refreshNews", "newsCollection is null")
e3ba048350db2a0e30fa4395e2fd0b04dcab5cc7

2020-06-25 12:09 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +                }
Je ne vois pas trop comment externaliser ça ... Mais j'ai fais des modifs donc peut-être que c'est mieux maintenant.

2020-06-25 12:12 UTC, martinsben commented on app/src/main/java/com/example/newsandroid/ui/topheadlines/TopHeadlinesFragment.kt
> +                }
85ce5d8144d11c248d29579a202882b4abfbeb6c

2020-06-26 08:58 UTC, PguOrange approved these changes

2020-06-26 09:15 UTC, merged